; Game modules in their original assembly order.
%INCLUDE "startup.asm"
%INCLUDE "roomdisp.asm"
%INCLUDE "parser.asm"
%INCLUDE "actions.asm"
%INCLUDE "encountr.asm"
%INCLUDE "scoring.asm"
%INCLUDE "combat.asm"
%INCLUDE "objects.asm"
%INCLUDE "movement.asm"
%INCLUDE "invinput.asm"
