; Native ATOM imports in output order.
%INCLUDE "const.asm"
%INCLUDE "prologue.asm"
%INCLUDE "game.asm"
%INCLUDE "commands.asm"
%INCLUDE "numbers.asm"
%INCLUDE "savecode.asm"
%INCLUDE "savedisk.asm"
%INCLUDE "system.asm"
%INCLUDE "strings.asm"
%INCLUDE "examtext.asm"
%INCLUDE "tables.asm"
%INCLUDE "vars.asm"
